language: julia

os: 
  - osx
  - linux

julia: 1.2

before_install:
  - julia deps/build.jl

notifications:
  email: true

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("GEMPIC")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: osx
      script:
        - julia --project=docs/ -e 'include("deps/build.jl"); Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jL
      name: "HTML"
      after_success: skip
