language: julia

os: 
  - osx
  - linux

julia: 1.1

notifications:
  email: true

after_success:
  - julia -e 'using Pkg; import GEMPIC; joinpath(dirname(pathof(GEMPIC)), "..", paths...); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: osx
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jL
      name: "HTML"
      after_success: skip
