language: julia

os: osx
julia: 1.0

notifications:
  email: true

codecov: true
 
jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: osx
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      name: "HTML"
